### ISSUE TITLE
PHP 8.1 compatibility

### ISSUE THREAD

**Issue by ewfisher** [hostmedia/whmcs-enom-balance-widget#2]
It appears that the module may not be PHP 8.1 compatible.  Getting the following error when trying to move to PHP 8.1 with WHMCS 8.6.  Moving back to PHP 7.4.x solves this problem immediately.

[Sat Nov 05 08:46:31.480048 2022] [proxy_fcgi:error] [pid 32663:tid 140227646732032] [client x.x.x.x:49058] AH01071: Got error 'PHP message: [WHMCS Application] ERROR: Error: Undefined constant "enom" in /var/www/vhosts/domain.com/httpdocs/modules/widgets/EnomBalance.php:53 Stack trace: #0 /var/www/vhosts/domain.com/httpdocs/vendor/whmcs/whmcs-foundation/lib/Module/AbstractWidget.php(0): eNomBalanceWidget->getData() #1 /var/www/vhosts/domain.com/httpdocs/vendor/whmcs/whmcs-foundation/lib/Module/AbstractWidget.php(0): WHMCS\\Module\\AbstractWidget->fetchData() #2 /var/www/vhosts/domain.com/whmcs_data/templates_c/3b39cb5820f2e5e6bd44da72cbf719bc264d579b_0.file.homepage.tpl.php(145): WHMCS\\Module\\AbstractWidget->render() #3 /var/www/vhosts/domain.com/httpdocs/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_6366582c183b04_55078502() #4 /var/www/vhosts/domain.com/httpdocs/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode() #5 /var/www/vhosts/domain.com/httpdocs/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templ...', referer: https://domain.com/admin/systemphpinfo.php

**Comment by ewfisher** [comment]
I believe this may work:

`--- EnomBalance.php.old	2022-10-15 17:01:51.883126251 -0400
+++ EnomBalance.php	2022-11-05 18:53:54.065663543 -0400
@@ -50,9 +50,9 @@
         $data = json_decode($json);
         
         $dataArray = array(
-            enom  => $data
-            , balance => $data->Balance
-            , availableBalance => $data->AvailableBalance
+            'enom' => $data
+            , 'balance' => $data->Balance
+            , 'availableBalance' => $data->AvailableBalance
         );
         
         return $dataArray;
`

**Comment by hostmedia** [comment]
This is being investigated and a fix will be released as soon as possible.

**Comment by hostmedia** [comment]
Resolved with update of MR 'Use of undefined constant' fix - further testing completed with further PHP versions with no errors.

Closing Issue.
