### ISSUE TITLE
PHP 8.1 Errors

### ISSUE THREAD

**Issue by RicRey1988** [hostmedia/whmcs-enom-balance-widget#3]
Hello, I get the following error when using php 8.1.

`Error: Undefined constant "enom" in /home/serviweb/public_html/shop/modules/widgets/EnomBalance.php:53
Stack trace:
#0 /home/serviweb/public_html/shop/vendor/whmcs/whmcs-foundation/lib/Module/AbstractWidget.php(0): eNomBalanceWidget->getData()
#1 /home/serviweb/public_html/shop/vendor/whmcs/whmcs-foundation/lib/Module/AbstractWidget.php(0): WHMCS\Module\AbstractWidget->fetchData(false)
#2 /home/serviweb/public_html/shop/ieuoiw9447_seguridad/templates_c4874_security/bd155a95d60873b6c06ab8f2267b8e15eae37481_0.file.homepage.tpl.php(160): WHMCS\Module\AbstractWidget->render()
#3 /home/serviweb/public_html/shop/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_651eda0d5866a1_52475370(Object(Smarty_Internal_Template))
#4 /home/serviweb/public_html/shop/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))
#5 /home/serviweb/public_html/shop/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))
#6 /home/serviweb/public_html/shop/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(232): Smarty_Internal_Template->render(false, 0)
#7 /home/serviweb/public_html/shop/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(116): Smarty_Internal_TemplateBase->_execute(Object(Smarty_Internal_Template), NULL, NULL, NULL, 0)
#8 /home/serviweb/public_html/shop/vendor/whmcs/whmcs-foundation/lib/Smarty.php(0): Smarty_Internal_TemplateBase->fetch('lara/homepage.t...', NULL, NULL, NULL, false, true, false)
#9 /home/serviweb/public_html/shop/vendor/whmcs/whmcs-foundation/lib/Admin.php(0): WHMCS\Smarty->fetch('lara/homepage.t...')
#10 /home/serviweb/public_html/shop/vendor/whmcs/whmcs-foundation/lib/Admin.php(0): WHMCS\Admin->output()
#11 /home/serviweb/public_html/shop/vendor/whmcs/whmcs-foundation/lib/Admin/Controller/HomepageController.php(0): WHMCS\Admin->display()
#12 [internal function]: WHMCS\Admin\Controller\HomepageController->index(Object(WHMCS\Http\Message\ServerRequest))
#13 /home/serviweb/public_html/shop/vendor/middlewares/utils/src/CallableHandler.php(26): call_user_func_array(Array, Array)
#14 /home/serviweb/public_html/shop/vendor/middlewares/fast-route/src/FastRoute.php(96): Middlewares\Utils\CallableHandler::execute(Array, Array)
#15 /home/serviweb/public_html/shop/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/HandleProcessor.php(0): Middlewares\FastRoute->process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate))
#16 /home/serviweb/public_html/shop/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/AssumingMiddlewareTrait.php(0): WHMCS\Route\Middleware\HandleProcessor->_process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate))
#17 /home/serviweb/public_html/shop/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\HandleProcessor->process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate))
#18 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}(Object(WHMCS\Http\Message\ServerRequest))
#19 /home/serviweb/public_html/shop/vendor/middlewares/utils/src/Delegate.php(31): call_user_func(Object(Closure), Object(WHMCS\Http\Message\ServerRequest))
#20 /home/serviweb/public_html/shop/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/DelegatingMiddlewareTrait.php(0): Middlewares\Utils\Delegate->process(Object(WHMCS\Http\Message\ServerRequest))
#21 /home/serviweb/public_html/shop/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Admin\ApplicationSupport\Route\Middleware\Assent->process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate))
#22 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}(Object(WHMCS\Http\Message\ServerRequest))
#23 /home/serviweb/public_html/shop/vendor/middlewares/utils/src/Delegate.php(31): call_user_func(Object(Closure), Object(WHMCS\Http\Message\ServerRequest))
#24 /home/serviweb/public_html/shop/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/DelegatingMiddlewareTrait.php(0): Middlewares\Utils\Delegate->process(Object(WHMCS\Http\Message\ServerRequest))
#25 /home/serviweb/public_html/shop/vendor/whmcs/whmcs-foundation/lib/Security/Middleware/Authorization.php(0): WHMCS\Security\Middleware\Authorization->process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate))
#26 /home/serviweb/public_html/shop/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/AbstractProxyMiddleware.php(0): WHMCS\Security\Middleware\Authorization->process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate))
#27 /home/serviweb/public_html/shop/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/AssumingMiddlewareTrait.php(0): WHMCS\Route\Middleware\AbstractProxyMiddleware->_process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate))
#28 /home/serviweb/public_html/shop/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\AbstractProxyMiddleware->process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate))
#29 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}(Object(WHMCS\Http\Message\ServerRequest))
#30 /home/serviweb/public_html/shop/vendor/middlewares/utils/src/Delegate.php(31): call_user_func(Object(Closure), Object(WHMCS\Http\Message\ServerRequest))
#31 /home/serviweb/public_html/shop/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/DelegatingMiddlewareTrait.php(0): Middlewares\Utils\Delegate->process(Object(WHMCS\Http\Message\ServerRequest))
#32 /home/serviweb/public_html/shop/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/AbstractProxyMiddleware.php(0): WHMCS\Admin\ApplicationSupport\Route\Middleware\Authentication->process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate))
#33 /home/serviweb/public_html/shop/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/AssumingMiddlewareTrait.php(0): WHMCS\Route\Middleware\AbstractProxyMiddleware->_process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate))
#34 /home/serviweb/public_html/shop/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\AbstractProxyMiddleware->process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate))
#35 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}(Object(WHMCS\Http\Message\ServerRequest))
#36 /home/serviweb/public_html/shop/vendor/middlewares/utils/src/Delegate.php(31): call_user_func(Object(Closure), Object(WHMCS\Http\Message\ServerRequest))
#37 /home/serviweb/public_html/shop/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/DelegatingMiddlewareTrait.php(0): Middlewares\Utils\Delegate->process(Object(WHMCS\Http\Message\ServerRequest))
#38 /home/serviweb/public_html/shop/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Admin\ApplicationSupport\Route\Middleware\DirectoryValidation->process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate))
#39 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}(Object(WHMCS\Http\Message\ServerRequest))
#40 /home/serviweb/public_html/shop/vendor/middlewares/utils/src/Delegate.php(31): call_user_func(Object(Closure), Object(WHMCS\Http\Message\ServerRequest))
#41 /home/serviweb/public_html/shop/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/BackendPsr7Response.php(0): Middlewares\Utils\Delegate->process(Object(WHMCS\Http\Message\ServerRequest))
#42 /home/serviweb/public_html/shop/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/BackendPsr7Response.php(0): WHMCS\Route\Middleware\BackendPsr7Response->_process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate))
#43 /home/serviweb/public_html/shop/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\BackendPsr7Response->process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate))
#44 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}(Object(WHMCS\Http\Message\ServerRequest))
#45 /home/serviweb/public_html/shop/vendor/middlewares/utils/src/Delegate.php(31): call_user_func(Object(Closure), Object(WHMCS\Http\Message\ServerRequest))
#46 /home/serviweb/public_html/shop/vendor/middlewares/utils/src/Dispatcher.php(56): Middlewares\Utils\Delegate->process(Object(WHMCS\Http\Message\ServerRequest))
#47 /home/serviweb/public_html/shop/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/BackendDispatch.php(0): Middlewares\Utils\Dispatcher->dispatch(Object(WHMCS\Http\Message\ServerRequest))
#48 /home/serviweb/public_html/shop/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/AssumingMiddlewareTrait.php(0): WHMCS\Route\Middleware\BackendDispatch->_process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate))
#49 /home/serviweb/public_html/shop/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\BackendDispatch->process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate))
#50 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}(Object(WHMCS\Http\Message\ServerRequest))
#51 /home/serviweb/public_html/shop/vendor/middlewares/utils/src/Delegate.php(31): call_user_func(Object(Closure), Object(WHMCS\Http\Message\ServerRequest))
#52 /home/serviweb/public_html/shop/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/RoutePathMatch.php(0): Middlewares\Utils\Delegate->process(Object(WHMCS\Http\Message\ServerRequest))
#53 /home/serviweb/public_html/shop/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/AssumingMiddlewareTrait.php(0): WHMCS\Route\Middleware\RoutePathMatch->_process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate))
#54 /home/serviweb/public_html/shop/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\RoutePathMatch->process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate))
#55 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}(Object(WHMCS\Http\Message\ServerRequest))
#56 /home/serviweb/public_html/shop/vendor/middlewares/utils/src/Delegate.php(31): call_user_func(Object(Closure), Object(WHMCS\Http\Message\ServerRequest))
#57 /home/serviweb/public_html/shop/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/WhitelistFilter.php(0): Middlewares\Utils\Delegate->process(Object(WHMCS\Http\Message\ServerRequest))
#58 /home/serviweb/public_html/shop/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/DelegatingMiddlewareTrait.php(0): WHMCS\Route\Middleware\WhitelistFilter->_process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate))
#59 /home/serviweb/public_html/shop/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\WhitelistFilter->process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate))
#60 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}(Object(WHMCS\Http\Message\ServerRequest))
#61 /home/serviweb/public_html/shop/vendor/middlewares/utils/src/Delegate.php(31): call_user_func(Object(Closure), Object(WHMCS\Http\Message\ServerRequest))
#62 /home/serviweb/public_html/shop/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/RoutableClientModuleRequest.php(0): Middlewares\Utils\Delegate->process(Object(WHMCS\Http\Message\ServerRequest))
#63 /home/serviweb/public_html/shop/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/AssumingMiddlewareTrait.php(0): WHMCS\Route\Middleware\RoutableClientModuleRequest->_process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate))
#64 /home/serviweb/public_html/shop/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\RoutableClientModuleRequest->process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate))
#65 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}(Object(WHMCS\Http\Message\ServerRequest))
#66 /home/serviweb/public_html/shop/vendor/middlewares/utils/src/Delegate.php(31): call_user_func(Object(Closure), Object(WHMCS\Http\Message\ServerRequest))
#67 /home/serviweb/public_html/shop/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/RoutableAdminRequestUri.php(0): Middlewares\Utils\Delegate->process(Object(WHMCS\Http\Message\ServerRequest))
#68 /home/serviweb/public_html/shop/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/AssumingMiddlewareTrait.php(0): WHMCS\Route\Middleware\RoutableAdminRequestUri->_process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate))
#69 /home/serviweb/public_html/shop/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\RoutableAdminRequestUri->process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate))
#70 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}(Object(WHMCS\Http\Message\ServerRequest))
#71 /home/serviweb/public_html/shop/vendor/middlewares/utils/src/Delegate.php(31): call_user_func(Object(Closure), Object(WHMCS\Http\Message\ServerRequest))
#72 /home/serviweb/public_html/shop/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/RoutableRequestUri.php(0): Middlewares\Utils\Delegate->process(Object(WHMCS\Http\Message\ServerRequest))
#73 /home/serviweb/public_html/shop/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/AssumingMiddlewareTrait.php(0): WHMCS\Route\Middleware\RoutableRequestUri->_process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate))
#74 /home/serviweb/public_html/shop/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\RoutableRequestUri->process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate))
#75 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}(Object(WHMCS\Http\Message\ServerRequest))
#76 /home/serviweb/public_html/shop/vendor/middlewares/utils/src/Delegate.php(31): call_user_func(Object(Closure), Object(WHMCS\Http\Message\ServerRequest))
#77 /home/serviweb/public_html/shop/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/RoutableRequestQueryUri.php(0): Middlewares\Utils\Delegate->process(Object(WHMCS\Http\Message\ServerRequest))
#78 /home/serviweb/public_html/shop/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/AssumingMiddlewareTrait.php(0): WHMCS\Route\Middleware\RoutableRequestQueryUri->_process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate))
#79 /home/serviweb/public_html/shop/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\RoutableRequestQueryUri->process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate))
#80 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}(Object(WHMCS\Http\Message\ServerRequest))
#81 /home/serviweb/public_html/shop/vendor/middlewares/utils/src/Delegate.php(31): call_user_func(Object(Closure), Object(WHMCS\Http\Message\ServerRequest))
#82 /home/serviweb/public_html/shop/vendor/middlewares/utils/src/Dispatcher.php(56): Middlewares\Utils\Delegate->process(Object(WHMCS\Http\Message\ServerRequest))
#83 /home/serviweb/public_html/shop/sisteprog/index.php(0): Middlewares\Utils\Dispatcher->dispatch(Object(WHMCS\Http\Message\ServerRequest))
#84 {main}`

**Comment by RicRey1988** [comment]
eNom Balance Widget Fix for WHMCS

Problem:

The original widget was encountering errors when trying to fetch and display the eNom balance on the WHMCS admin dashboard.

Solution:

The following changes were made to the widget's code to address the issue:

Object Properties vs. Array Keys

In the original code, data was being accessed as object properties:

In the revised version, we converted the data to an associative array and accessed the values using array keys:

Key/Property Verification

Added isset() checks to ensure keys/properties were present before attempting to access them:

Error Handling

Error handling was similarly addressed, ensuring that if an error was present, it was handled appropriately and a useful error message was provided.

Revised Code:

```
<?php

add_hook('AdminHomeWidgets', 1, function() {
    return new eNomBalanceWidget();
});

class eNomBalanceWidget extends \WHMCS\Module\AbstractWidget
{
    protected $title = 'eNom Balance';
    protected $description = 'Widget provides you with your eNom balance on your admin dashboard. Created by Host Media.';
    protected $weight = 150;
    protected $columns = 1;
    protected $cache = true;
    protected $cacheExpiry = 120;

    public function getData()
    {
        $enomusername = 'YOUR-ENOM-USERNAME-HERE';
        $enompassword = 'YOUR-ENOM-PASSWORD-HERE';
        $enomapiurl = 'https://reseller.enom.com/';
        $enomapiurl .= 'interface.asp?command=GetBalance&uid='.$enomusername.'&pw='.$enompassword.'&responsetype=xml';
        
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $enomapiurl);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 10);
        curl_setopt($ch, CURLOPT_TIMEOUT, 10);
        $result = curl_exec($ch);
        curl_close($ch);
        
        $xml = simplexml_load_string($result);
        $json = json_encode($xml);
        $data = json_decode($json, true);
        
        return $data;
    }

    public function generateOutput($data)
    {
        if (isset($data['ErrCount']) && $data['ErrCount'] > 0) {
            $error = isset($data['errors']['Err1']) ? $data['errors']['Err1'] : 'Unknown error';
            return <<<EOF
    <div class="widget-content-padded">
        <strong>There was an error:</strong><br/>
        {$error}
    </div>
EOF;
        }
        
        $balance = isset($data['Balance']) ? $data['Balance'] : 'N/A';
        $availableBalance = isset($data['AvailableBalance']) ? $data['AvailableBalance'] : 'N/A';
        
        return <<<EOF
    <div class="widget-content-padded">
        <div class="row text-center">
            <div class="col-sm-6">
                <h4><strong>&#36;{$balance}</strong></h4>
                Balance
            </div>
            <div class="col-sm-6">
                <h4><strong>&#36;{$availableBalance}</strong></h4>
                Available Balance
            </div>
        </div>
        <div class="row text-center" style="margin-top: 20px;">
            <a href="https://www.enom.com/myaccount/RefillAccount.aspx" class="btn btn-default btn-sm" target="_blank"><i class="fas fa-credit-card fa-fw"></i> Refill Account</a>
        </div>
    </div>
EOF;
    }
}
```

This revised code ensures robustness, especially when working with external APIs and data. It's crucial to handle situations where data might not be present or might not be exactly as expected.

`$balance = isset($data['Balance']) ? $data['Balance'] : 'N/A';`


`$data['Balance']`


`$data->Balance`

**Comment by hostmedia** [comment]
Sorry for the delay in our reply, we will have a look at your suggested code and implement once tested. Thank you for supporting the WHMCS widget with improvements :)

**Comment by deltaforce** [comment]
you need to update the version number, it still says v 1.1, so I thought I have the latest version, as mine also says v1.1 which I obviously don't as mine was installed 1 year ago.

**Comment by hostmedia** [comment]
Patch version number was applied to ensure clarity of the version. This was missed due to a 3rd party merge which when reviewed an update to the version number wasn't applied.
