### ISSUE TITLE
changes required to API authentication

### ISSUE THREAD

**Issue by deltaforce** [hostmedia/whmcs-enom-balance-widget#4]
got this from enom

Note for API users: if you currently use your Enom account password to send API calls, you'll need to switch to a token before resetting your password. You must reset your password before Sept. 10, 2024.

so you need to update this to use token instead of password

**Comment by deltaforce** [comment]
as advised above, the widget has now stopped working

**Comment by hostmedia** [comment]
Our production and test versions using the eNom username & password continue to work for us. Do you have a link to an eNom documentation for this shift for API calls we can check?

We have also checked the eNom documentation and this command and the examples continue to show as we have coded: https://api.enom.com/docs/getbalance

Thank you.
